AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a simple EC2 instance

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    Description: EC2 instance type

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID where the EC2 instance will be launched

  AMIId:
    Type: AWS::EC2::Image::Id
    Default: ami-0dee22c13ea7a9a67
    Description: AMI ID for the EC2 instance

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: !Ref AMIId
      SubnetId: !Ref SubnetId
      AssociatePublicIpAddress: true
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install -y openjdk-17-jre jenkins
          sudo systemctl start jenkins
          sudo systemctl enable jenkins
          
Outputs:
  InstanceId:
    Value: !Ref EC2Instance
    Description: The Instance ID of the EC2 instance

  PublicIP:
    Value: !GetAtt EC2Instance.PublicIp
    Description: Public IP address of the EC2 instance
